apiVersion: v1
kind: Service
metadata:
  namespace: warnet
  annotations:
    kompose.cmd: kompose convert --controller statefulset
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: rpc
  name: rpc
spec:
  clusterIP: None
  ports:
    - name: headless
      port: 9276
      targetPort: 0
  selector:
    io.kompose.service: rpc
status:
  loadBalancer: {}
