apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: warnet
  name: pod-reader-exec
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["pods/log"]  # Granting permission to access pod logs
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-exec-pods
  namespace: warnet
subjects:
- kind: ServiceAccount
  name: default
  namespace: warnet
roleRef:
  kind: Role
  name: pod-reader-exec
  apiGroup: rbac.authorization.k8s.io
