apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rpc
  namespace: warnet
spec:
  serviceName: "rpc"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rpc
  template:
    metadata:
      labels:
        io.kompose.service: rpc
    spec:
      containers:
      - name: warnet-rpc
        imagePullPolicy: Always
        image: bitcoindevproject/warnet-rpc:0.1
        ports:
        - containerPort: 9276

