[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "warnet"
description = "Monitor and analyze the emergent behaviours of bitcoin networks"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["bitcoin", "warnet"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = []
dynamic = ["version"]

[project.optional-dependencies]
server = [
    "docker==6.1.3",
    "flask==2.3.3",
    "Flask-JSONRPC==2.2.2",
    "jsonschema",
    "jsonrpcserver==5.0.3",
    "kubernetes~=28.1.0",
    "networkx==3.1",
    "numpy==1.26.0",
]

cli = [
    "click==8.1.7",
    "jsonrpcclient==4.0.0",
    "rich==13.5.2",
    "tabulate==0.9.0",
    "PyYAML==6.0.1",
]

all = ["warnet[cli,server]"]


[project.scripts]
warnet = "warnet.server:run_server"
warcli = "warnet.cli.main:cli"

[tool.ruff]
extend-exclude = ["src/test_framework/*.py"]
line-length = 100
indent-width = 4
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501"] # Line too long
