apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {{- .Values.caddyConfig | nindent 4 }}
  index: |
    {{- .Values.htmlConfig | nindent 4 }}
