apiVersion: v1
kind: Pod
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
    app: {{ include "caddy.fullname" . }}
spec:
  restartPolicy: "{{ .Values.restartPolicy }}"
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: web
          containerPort: {{ .Values.port }}
          protocol: TCP
      livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 8 }}
      readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      volumeMounts:
        {{- toYaml .Values.volumeMounts | nindent 8 }}
  volumes:
    {{- toYaml .Values.volumes | nindent 4 }}
