apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
    app: {{ include "caddy.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: web
      protocol: TCP
      name: http
  selector:
    {{- include "caddy.selectorLabels" . | nindent 4 }}
