name: build-docker-rpc-images

on:
  workflow_run:
    workflows: ["test", "ruff"]
    types:
      - completed
    branches:
      - 'main'

jobs:
  check-prerequisite-workflows:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.check-conclusion.outputs.success }}
    steps:
      - name: Check prerequisite workflow conclusion
        id: check-conclusion
        run: |
          conclusion="${{ github.event.workflow_run.conclusion }}"
          if [ "$conclusion" = "success" ]; then
            echo "::set-output name=success::true"
          else
            echo "::set-output name=success::false"
            exit 1
          fi

  build-image:
    needs: check-prerequisite-workflow
    if: needs.check-prerequisite-workflow.outputs.success == 'true'
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_RPC_REPO }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: src/templates/rpc/Dockerfile_rpc
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_RPC_REPO }}:latest
          cache-to: type=inline
