name: deploy
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.conclusion == 'success'
    # DISABLE FOR REWRITE
    if: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_RPC_REPO }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            maintainer=bitcoindevproject
            org.opencontainers.image.title=warnet-rpc
            org.opencontainers.image.description=Warnet RPC server
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build production RPC image
        uses: docker/build-push-action@v5
        with:
          file: resources/images/rpc/Dockerfile_prod
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build dev RPC image
        uses: docker/build-push-action@v5
        with:
          file: resources/images/rpc/Dockerfile_dev
          platforms: linux/amd64,linux/arm64
          context: resources/images/rpc
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_RPC_REPO }}:dev
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
