name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/build_branch_test.py
  scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/scenarios_test.py
  rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/rpc_test.py
  rpc-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: medyagh/setup-minikube@master
      - run: pip install --upgrade pip
      - run: pip install -e .
      - run: just kd
      - run: kubectl wait --for=condition=Ready --timeout=2m pod rpc-0
      - run: |
          sleep 60
          kubectl port-forward --v=8 svc/rpc 9276:9276 &
          sleep 5
          ./test/rpc_test.py k8s
      - run: just kdd
  graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/test_graph.py
  ln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/ln_test.py
