name: Test

on: [push, pull_request]

jobs:
  rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: ./test/rpc_test.py
  rpc-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: medyagh/setup-minikube@master
      - run: pip install --upgrade pip
      - run: pip install -e .
      - run: just start
      - run: kubectl wait --for=condition=Ready --timeout=2m pod rpc-0
      - run: |
          kubectl port-forward svc/rpc 9276:9276 &
          ./test/rpc_test.py k8s
      - run: just stop
