name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  build-image:
    needs: [ruff]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          file: src/templates/rpc/Dockerfile_rpc
          context: .
          tags: warnet/dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/warnet.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: warnet
          path: /tmp/warnet.tar
  test:
    needs: [build-image]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [compose, k8s]
        test: [scenarios_test.py, rpc_test.py, graph_test.py, ln_test.py, get_service_ip_test.py]
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v1
      - if: matrix.backend == 'compose'
        uses: ./.github/actions/compose
      - if: matrix.backend == 'k8s'
        uses: ./.github/actions/k8s
      - if: matrix.backend == 'k8s'
        run: |
          kubectl port-forward svc/rpc 9276:9276 &
      - name: Run tests
        run: |
          uv venv
          uv pip install .[server]
          uv run ./test/${{matrix.test}} ${{matrix.backend}}
  build-test:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/setup-cached-uv@v1
      - uses: ./.github/actions/compose
      - run: |
          uv venv
          uv pip install .[server]
          uv run ./test/build_branch_test.py compose
